include(GitCommit)
get_commit_hash(GIT_COMMIT)

set(CONFIGURE_COMMAND
    "cmake -DBTOP_STATIC=${BTOP_STATIC} -DBTOP_FORTIFY=${BTOP_FORTIFY} -DBTOP_ENABLE_GPU=${BTOP_ENABLE_GPU}"
)

get_filename_component(CXX_COMPILER_BASENAME "${CMAKE_CXX_COMPILER}" NAME)
set(COMPILER "${CXX_COMPILER_BASENAME}")
set(COMPILER_VERSION "${CMAKE_CXX_COMPILER_VERSION}")

configure_file(config.h.in ${CMAKE_CURRENT_BINARY_DIR}/config.h @ONLY IMMEDIATE)
target_include_directories(btop PRIVATE ${CMAKE_CURRENT_BINARY_DIR})
