include(CheckCXXCompilerFlag)
include(CheckLinkerFlag)

macro(mangle_name str output)
  string(STRIP "${str}" strippedStr)
  string(REGEX REPLACE "^/" "" strippedStr "${strippedStr}")
  string(REGEX REPLACE "^-+" "" strippedStr "${strippedStr}")
  string(REGEX REPLACE "-+$" "" strippedStr "${strippedStr}")
  string(REPLACE "-" "_" strippedStr "${strippedStr}")
  string(REPLACE "=" "_EQ_" strippedStr "${strippedStr}")
  string(REPLACE "+" "X" strippedStr "${strippedStr}")
  string(TOUPPER "${strippedStr}" ${output})
endmacro()

macro(add_cxx_flag target flag)
  target_compile_options(${target} PRIVATE ${flag})
endmacro()

macro(add_cxx_flag_if target condition flag)
  if(${condition})
    add_cxx_flag(${target} ${flag})
  endif()
endmacro()

macro(add_cxx_flags_if_supported target)
  foreach(flag ${ARGN})
    mangle_name(${flag} flagname)
    check_cxx_compiler_flag(${flag} "CXX_SUPPORTS_${flagname}_FLAG")
    add_cxx_flag_if(${target} CXX_SUPPORTS_${flagname}_FLAG ${flag})
  endforeach()
endmacro()
